FROM php:fpm AS Darksoft2021-simple-php-daemon

RUN apt-get update && apt-get install -y \
libmcrypt-dev 

RUN docker-php-ext-install -j$(nproc) sockets



LABEL multi.com.example.vendor="DarkSoft2021" \
      multi.version="2.6" \
      multi.description="Learn docker containers" \
      multi.changed="Add php-daemon. Listen 31337 port."

EXPOSE 31337

WORKDIR /docker/learning-docker/l5

COPY . .

ENTRYPOINT  ["php", "simple-daemon.php"]
